name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      echo " This is my secret ${{secret.LHV_SECRET}} "
      uses: docker/build-push-action@v1
      with:
        push: false
