name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    run:
      echo " This is my secret ${{secret.LHV_SECRET}} "
    steps:
    - name: Buil
      run:
       echo " This is my secret ${{secret.LHV_SECRET}} "
